sudo: required
dist: trusty
language: node

before_script:
  # install v6.x of nodejs
   - nvm install 12.0
  #install yarn globally
   - npm install -g yarn
  # yarn install is like npm install
   - yarn install
   - yarn add bower
   - yarn add pulp
   - yarn add purescript

script:
  - bower install
  - pulp build
  - pulp test
